language: python
python:
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --ignore-pipfile --deploy --system --dev

jobs:
  include:
    - stage: check
      script: make check
    - stage: tests
      script: make tests
