name: tests
on:
  push:
    branches:
    - master
    - dev
    tags:
    - v*
  pull_request:
    types:
    - synchronize
    - opened
    - reopened
jobs:
  test:
    name: python-${{ matrix.python }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python:
        - 3.9
        - 3.10
        - 3.11
        os:
        - ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Poetry
      run: pip -q --no-input install poetry
    - name: Install Poetry dependencies
      run: poetry install -n --no-root
    - name: Run linters
      run: poetry run make check
    - name: Run tests
      run: poetry run make tests
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      if: matrix.python == 3.9 && matrix.os == 'ubuntu-latest'
